INSERT INTO USERS(ID, LOGIN, PASSWORD) VALUES (1, 'admin', '222222');
INSERT INTO USERS(ID, LOGIN, PASSWORD) VALUES (2, 'moder', '111111');

INSERT INTO ROLES(ID, ROLE) VALUES (1, 'admin');
INSERT INTO ROLES(ID, ROLE) VALUES (2, 'moderator');

INSERT INTO USER_ROLES(user_id, role_id) VALUES (1, 1);
INSERT INTO USER_ROLES(user_id, role_id) VALUES (2, 2);